# -*- coding: utf-8 -*-
"""E6 -S316063569.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wM7Lr4aXZMyA6Sd2v-dGvSJ1UarNUhQS
"""

from google.colab import drive
drive.mount('/content/drive')

import os
folder_path='/content/drive/MyDrive/תרגיל 6'
os.chdir(folder_path)

import pandas as pd
import numpy as np

"""**שאלה 1**"""

def ReadData (Str,Tpl):
  if isinstance(Str,str) != True:
    return None

  Excel = pd.read_excel(Str)
  FrameExcel = pd.DataFrame(data=Excel, columns=Tpl)
  Mat = FrameExcel.to_numpy() 

  return Mat

data2 = ReadData('data_2.xlsx',('a','b','e'))
print('data2:\n{}\n'.format(data2))

data1 = ReadData('data_1.xlsx',('X','Z'))
print('data1[:10]:\n{}\n'.format(data1[:10]))

data2 = 'data_2.xlsx'
DR = pd.read_excel(data2)
print(DR)

data1 = 'data_1.xlsx'
DR = pd.read_excel(data1)
print(DR)

"""**שאלה 2**"""

def PearsonCorrelation (X,Y):
  R=(np.sum((X-np.mean(X))*(Y-np.mean(Y))))/(np.sqrt(np.sum((X-np.mean(X))**2)*np.sum((Y-np.mean(Y))**2)))
  return R

X = np.array([9,7,5,3,1])
Y = np.array([10,6,1,5,3])
R1= PearsonCorrelation(X ,Y)
print('R1: {}\n'.format(R1))

X = np.array([1,0,1])
Y = np.array([0,2,1])
R2= PearsonCorrelation(X ,Y)
print('R2: {}\n'.format(R2))

"""**שאלה 3**"""

import matplotlib.pyplot as plt

def PlotMyData (Mat,List_num,List_names):
  NumOfWin = range(len(List_names))
  #if NumOfWin in range(Len):
  a = int(len(List_num[NumOfWin][0]))
  b = int(len(List_num[NumOfWin][1]))
  X = Mat [:, a]
  Y = Mat [:, b]
  R= PearsonCorrelation(X,Y)

  sub1 = List_names [NumOfWin][0]
  sub2 = List_names [NumOfWin][1]

  plt.figure()
  plt.subplot(len(List_names),1, NumOfWin+1)
  plt.title('{}: R{}'.format(sub1,sub2,R))
  plt.plot(X)
  plt.plot(Y)
  plt.legend(('{}'.format(sub1),'{}'.format(sub2)))
  plt.show()

data = ReadData('data_1.xlsx',('X','Y','Z'))
PlotMyData(data, ['01','12','02'],['XY','YZ','XZ'])